In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df_2024_1 = pd.read_csv('ca-2024-01.csv', sep=';', decimal=',')
df_2024_2 = pd.read_csv('ca-2024-02.csv', sep=';', decimal=',')
df_2025_1 = pd.read_csv('ca-2025-01.csv', sep=';', decimal=',')
df_2025_2 = pd.read_csv('ca-2025-02.csv', sep=';', decimal=',')

C:\Users\gabriel.goitia\AppData\Local\Temp\ipykernel_21568\901081134.py:7: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Unidade de Medida, 13: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025_1 = pd.read_csv('ca-2025-01.csv', sep=';', decimal=',')

In [6]:
df = pd.concat([df_2024_1, df_2024_2,
              df_2025_1, df_2025_2],
              ignore_index=True)
print(df.shape)

(1712267, 16)

In [7]:
display(df.head(10))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
1,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA ADITIVADA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
2,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,DIESEL S10,01/01/2024,5.93,NaN,R$ / litro,VIBRA
3,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,ETANOL,01/01/2024,3.99,NaN,R$ / litro,VIBRA
4,NE,AL,ARAPIRACA,AUTO POSTO SAO FRANCISCO LTDA,12.706.529/0001-04,RUA SAO FRANCISCO,274,NaN,CENTRO,57300-080,GASOLINA,01/01/2024,5.48,NaN,R$ / litro,VIBRA
5,NE,AL,ARAPIRACA,IBN PINTO E SILVA & CIA LTDA,01.242.690/0001-58,RODOVIA AL-110,678,KM 70,CANAFISTULA,57302-802,GNV,01/01/2024,4.69,NaN,R$ / m³,BRANCA
6,NE,AL,ARAPIRACA,IBN PINTO E SILVA & CIA LTDA,01.242.690/0001-58,RODOVIA AL-110,678,KM 70,CANAFISTULA,57302-802,GASOLINA,01/01/2024,5.69,NaN,R$ / litro,BRANCA
7,NE,AL,ARAPIRACA,IBN PINTO E SILVA & CIA LTDA,01.242.690/0001-58,RODOVIA AL-110,678,KM 70,CANAFISTULA,57302-802,GASOLINA ADITIVADA,01/01/2024,5.89,NaN,R$ / litro,BRANCA
8,NE,AL,ARAPIRACA,IBN PINTO E SILVA & CIA LTDA,01.242.690/0001-58,RODOVIA AL-110,678,KM 70,CANAFISTULA,57302-802,DIESEL,01/01/2024,5.99,NaN,R$ / litro,BRANCA
9,NE,AL,ARAPIRACA,IBN PINTO E SILVA & CIA LTDA,01.242.690/0001-58,RODOVIA AL-110,678,KM 70,CANAFISTULA,57302-802,ETANOL,01/01/2024,3.99,NaN,R$ / litro,BRANCA

In [8]:
df_gas_rj = df.loc[(df['Estado - Sigla'] =='RJ') & (df['Produto'] == 'GASOLINA')]

In [9]:
df_munic_rj_gas = df_gas_rj.groupby('Municipio')['Valor de Venda'].mean().reset_index()

df_munic_rj_gas.sort_values(by='Valor de Venda', ascending=False, inplace=True)

df_munic_rj_gas

                      Municipio  Valor de Venda
29                    TRES RIOS        6.591634
0                ANGRA DOS REIS        6.521620
18                   PETROPOLIS        6.479639
2                BARRA DO PIRAI        6.375640
11                        MACAE        6.364828
16                NOVA FRIBURGO        6.357044
10                    ITAPERUNA        6.352013
6         CAMPOS DOS GOYTACAZES        6.338306
5                     CABO FRIO        6.322089
23  SAO FRANCISCO DE ITABAPOANA        6.214804
31                VOLTA REDONDA        6.206265
1                      ARARUAMA        6.158700
27                    SAQUAREMA        6.133649
3                   BARRA MANSA        6.092928
30                      VALENCA        6.047609
26                     SAPUCAIA        5.994565
22       SANTO ANTONIO DE PADUA        5.962665
21               RIO DE JANEIRO        5.930698
13                       MARICA        5.899534
19                      RESENDE        5.885842
24                  SAO GONCALO        5.855353
20                   RIO BONITO        5.848639
8                      ITABORAI        5.842281
17                  NOVA IGUACU        5.807970
7               DUQUE DE CAXIAS        5.793860
25           SAO JOAO DE MERITI        5.780650
14                    NILOPOLIS        5.769526
15                      NITEROI        5.757424
4                  BELFORD ROXO        5.752965
12                         MAGE        5.615435
9                       ITAGUAI        5.602390
28                  TERESOPOLIS        5.508448

In [10]:
df_posto_rj = df_gas_rj.groupby('Revenda')['Valor de Venda'].mean().reset_index()
df_posto_rj.sort_values(by='Valor de Venda', ascending=False, 
inplace=True)
df_posto_rj

                                               Revenda  Valor de Venda
690                        POSTO JARDIM OCEANICO LTDA.        7.750674
76   AUTO POSTO DE COMBUSTIVEIS M C 2000 DE SANTA I...        7.415000
776                        POSTO SATURNO FRIBURGO LTDA        6.824444
1                   A C TRANCOZO M B COMBUSTIVEIS LTDA        6.742157
304  COMERCIO DE PETROLEO E DERIVADOS COND DO RIO N...        6.713529
..                                                 ...             ...
668                             POSTO FLAMAREDI EIRELI        5.282000
571              POSTO DE GASOLINA JARDIM SULACAP LTDA        5.226364
569              POSTO DE GASOLINA JAGUAR DO ANIL LTDA        5.156667
567                     POSTO DE GASOLINA ITAJUBA LTDA        5.090000
560                        POSTO DE GASOLINA GALP LTDA        5.090000

[872 rows x 2 columns]

In [11]:
array_posto = np.array(df_posto_rj['Valor de Venda'])

minimo = np.min (array_posto)
maximo = np.max (array_posto)
amplitude = maximo - minimo
q1 = np.percentile(array_posto, 25)
q3 = np.percentile(array_posto, 75)
iqr = q3 - q1
limite_superior = q3 + (1.5*iqr)
limite_inferior = q1 - (1.5*iqr)

print(f'Limite Superior {limite_superior}')
print(f'Limite Inferior {limite_inferior}')

Limite Superior 6.936768796992482
Limite Inferior 4.945385338345865

In [14]:
df_munic_rj = df.loc[(df['Municipio'] == 'RIO DE JANEIRO') & (df
['Produto'] == 'GASOLINA')]

df_munic_rj.head(3)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
2309,SE,RJ,RIO DE JANEIRO,POSTO DE COMBUSTIVEIS CANDIDO BENICIO LTDA,08.833.560/0001-39,RUA CANDIDO BENICIO,2742,NaN,PRACA SECA,22733-001,GASOLINA,02/01/2024,5.29,NaN,R$ / litro,VIBRA
2313,SE,RJ,RIO DE JANEIRO,POSTO E GARAGEM DOM HELDER CAMARA LTDA,04.802.584/0001-70,AVENIDA DOM HELDER CAMARA,4539,NaN,DEL CASTILHO,20771-000,GASOLINA,02/01/2024,5.69,NaN,R$ / litro,RAIZEN
2319,SE,RJ,RIO DE JANEIRO,POSTO DE GASOLINA ALTO ASTRAL DO MEIER LTDA,08.408.393/0001-89,RUA MEDINA,137,NaN,MEIER,20735-130,GASOLINA,02/01/2024,5.19,NaN,R$ / litro,BRANCA

In [16]:
df_bairro_rj = df_munic_rj.groupby('Bairro')['Valor de Venda'].mean().reset_index()

df_bairro_rj.sort_values(by='Valor de Venda', ascending=False,
inplace=True)

df_bairro_rj

             Bairro  Valor de Venda
23         FLAMENGO        6.696667
41  JARDIM BOTANICO        6.614615
44            LAGOA        6.505385
55  PARQUE FLAMENGO        6.454706
21          ESTACIO        6.416882
..              ...             ...
50            MEIER        5.340000
37           JACARE        5.310000
49   MARIA DA GRACA        5.290000
43   JARDIM SULACAP        5.226364
3              ANIL        5.156667

[85 rows x 2 columns]